describe('cadastra conta empresa no sistema', () => {
  it('deve criar uma conta valida no site', () => {
    cy.visit('http://localhost:5173/cadastro')
    cy.get('#nome').type('empresa-name')
    cy.get('#email').type('empresa@gmail.com')
    cy.get('#senha').type('12345')
    cy.get('[value="empresa"]').click()
    cy.get('.custom-button').click()
    cy.get(':nth-child(1) > select').select('medio')
    cy.get(':nth-child(1) > #inicio').type("07:00")
    cy.get(':nth-child(3) > #inicio').type('19:00')
    cy.get(':nth-child(3) > select').select('taguatinga')
    cy.get(':nth-child(4) > select').select('casa_apt')
    cy.get('#pequeno_preco').type('2000')
    cy.get('#medio_preco').type('5000')
    cy.get('#grande_preco').type('8000')
    cy.get('.button-centralizado > .custom-button').click()
  })
})